### ISSUE TITLE
Mutating a kredis_hash using []= doesn't trigger callbacks

### ISSUE THREAD

**Issue by julianrubisch** [rails/kredis#53]
```rb
class Foo < ApplicationRecord
  kredis_hash :bar, after_change: :touch_record

  def touch_record
    touch
  end
end
```

```rb
Foo.new.bar["test"] = "baz"
``` 

doesn't run the callback while

```rb
Foo.new.bar.update "test" => "baz"
```

does.

**Comment by kaspth** [comment]
Looks like I last audited and updated the callbacks here https://github.com/rails/kredis/commit/90176e63609414171b6fff3c1e3919c7f710d138#diff-bca937ce1c8f9956e9a4ea2888cb1ce8ed352a40b6504e1a2c82c690806c5356 but that was after adding `[]=` in https://github.com/rails/kredis/commit/571d1b12c8c06f8092fa7cbbc10c15fbf4e00fd9#diff-57e4e692256be3d5fd3f251856412fc91fbc7750405934285fe1dc28823f1714

And now I remember I didn't add `[]=` because I figured the internal `update` call would be caught, but of course that's not on the proxy.

Do you want to add `[]=` with a test? Looks like we also need to add `remove` from #41.

**Comment by julianrubisch** [comment]
Yup, I can tackle this later this week.
