### ISSUE TITLE
Request thread caching

### ISSUE THREAD

**Issue by tleish** [rails/kredis#67]
[Rails ActiveRecord SQL Caching](https://guides.rubyonrails.org/caching_with_rails.html#sql-caching) caches the same query in a single request thread and only queries the database once.  Kredis on the other hand queries redis every time in a request thread .

Thoughts on setting up similar request thread caching with Kredis keys?

**Comment by dhh** [comment]
Have you hit a specific case where this was the bottleneck? SQL queries have a tendency to be far more expensive to run, so the cache has the potential of saving a lot more than your typical redis query. I ask because the introduction of a cache is always a complication. Potential for bugs and stale data. So we should be sure that the upside is worth it.

**Comment by tleish** [comment]
> Have you hit a specific case where this was the bottleneck?

Not yet, but if I can avoid extra calls to Redis when a simple memoization is possible and slow Redis down scaling requirements... I'd prefer the memoization.  

For now, we add memoization inside a method which calls the kredis value methods.  I was hoping to avoid the broilerplate code

**Comment by dhh** [comment]
I think it's worth waiting until we hit an actual bottleneck. The complexity involved with keeping the cache, expiring the cache, etc is significant. I don't think it's justified preemptively.
